---

- name: Configure AWS ASG and LC
  hosts: localhost
  vars_files: 
    - vars.yml


  tasks: 

  - name: Create LC 
    ec2_lc:
      name: "{{ launch_config }}"
      image_id: "{{ base_ami }}"
      key_name: "{{ key_pair_name }}"
      region: us-west-1
      security_groups: [ "{{ security_group }}" ]
      user_data: "{{ lookup('file', 'user_data.sh') }}"
      instance_type: t2.micro
      volumes:
      - device_name: /dev/sda1
        volume_size: 100
        device_type: gp2
        delete_on_termination: false
      - device_name: /dev/sdb
        ephemeral: ephemeral0


  - ec2_asg:
      name: statusim_asg
      availability_zones: [ 'us-west-1b', 'us-west-1c' ]
      launch_config_name: "{{ launch_config }}"
      region: us-west-1
      min_size: 1
      max_size: 1
      desired_capacity: 1
      tags:
        - environment: demo
        - Name: eth-miner
